### ISSUE TITLE
padronizar página de cadastro c/ página principal

### ISSUE THREAD

**Issue by murilobauerc** [luccamac/twitter-using-spring#8]
- [ ] refatorar arquivo de cadastro

**Comment by luccamac** [comment]
![image](https://user-images.githubusercontent.com/37119928/44870014-5d318180-ac65-11e8-84c2-67dd582155ee.png)
dando erro ao tentar criar um usuário

**Comment by luccamac** [comment]
![image](https://user-images.githubusercontent.com/37119928/44871475-3d9c5800-ac69-11e8-8ffd-e0811ac78c72.png)
entra na página mas não cria usuário, dispara o erro acima

**Comment by luccamac** [comment]
```
javax.validation.ConstraintViolationException: Validation failed for classes [twitter.app.Message] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='não pode ser nulo', propertyPath=body, rootBeanClass=class twitter.app.Message, messageTemplate='{javax.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='não pode ser nulo', propertyPath=username, rootBeanClass=class twitter.app.Message, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
```
pelo que entendi ele não tá referenciando e criando o objeto usuário

**Comment by luccamac** [comment]
![image](https://user-images.githubusercontent.com/37119928/44872538-31fe6080-ac6c-11e8-91ad-b0dc8fadc113.png)
TOPPEN!
